version: 2
jobs:
  build:
    docker:
      - image: node:8.1
    working_directory: ~/uikit-site
    branches:
        only:
          - master
    steps:
      - run:
          name: Update Environment
          command: apt-get update && apt-get -y install rsync
      - checkout
      - run:
          name: Dependencies
          command: |
            yarn
      - run:
          name: Compile
          command: |
            yarn run compile
      - run:
          name: Replace Build Number
          command: |
            sed -i -- "s/{{BUILD}}/$CIRCLE_BUILD_NUM/g" index.html
            sed -i -- "s/{{BUILD}}/$CIRCLE_BUILD_NUM/g" docs/index.html
      - run:
          name: Transfer Files
          command: rsync -avze "ssh -o StrictHostKeyChecking=no" --delete --include "node_modules/uikit" --exclude "yarn.lock" --exclude "migrate.min.js" --exclude "node_modules" --exclude "v2" --exclude "fonts" --exclude ".git*" --exclude ".circleci" . $UIKIT_SERVER
